#!/usr/bin/env python3
from typing import Optional


class Service:
  def __init__(self, should_log: bool, frequency: float, decimation: Optional[int] = None, big_queue: bool = False):
    self.should_log = should_log
    self.frequency = frequency
    self.decimation = decimation

    # this flag makes the MSGQ rinbguffer 1MB for larger messages vs 500K.
    # TODO: currently these were chosen with selfdrive/debug/analyze-msg-size.py,
    # but it should be determined automatically from the capnp schema.
    self.big_queue = big_queue


SERVICE_LIST = {
  # service: Service(should_log, frequency, qlog decimation (optional), big_queue (optional))
  # note: the "EncodeIdx" packets will still be in the log
  "gyroscope": Service(True, 104., 104),
  "accelerometer": Service(True, 104., 104),
  "magnetometer": Service(True, 25.),
  "lightSensor": Service(True, 100., 100),
  "temperatureSensor": Service(True, 2., 200),
  "gpsNMEA": Service(True, 9.),
  "deviceState": Service(True, 2., 1),
  "touch": Service(True, 20., 1),
  "can": Service(True, 100., 2053, big_queue=True),  # decimation gives ~3 msgs in a full segment
  "controlsState": Service(True, 100., 10),
  "selfdriveState": Service(True, 100., 10),
  "pandaStates": Service(True, 10., 1),
  "peripheralState": Service(True, 2., 1),
  "radarState": Service(True, 20., 5),
  "roadEncodeIdx": Service(False, 20., 1),
  "liveTracks": Service(True, 20.),
  "sendcan": Service(True, 100., 139),
  "logMessage": Service(True, 0.),
  "errorLogMessage": Service(True, 0., 1),
  "liveCalibration": Service(True, 4., 4),
  "liveTorqueParameters": Service(True, 4., 1),
  "liveDelay": Service(True, 4., 1),
  "androidLog": Service(True, 0.),
  "carState": Service(True, 100., 10),
  "carControl": Service(True, 100., 10),
  "carOutput": Service(True, 100., 10),
  "longitudinalPlan": Service(True, 20., 10),
  "driverAssistance": Service(True, 20., 20),
  "procLog": Service(True, 0.5, 15),
  "gpsLocationExternal": Service(True, 10., 10),
  "gpsLocation": Service(True, 1., 1),
  "ubloxGnss": Service(True, 10.),
  "qcomGnss": Service(True, 2.),
  "gnssMeasurements": Service(True, 10., 10),
  "clocks": Service(True, 0.1, 1),
  "ubloxRaw": Service(True, 20.),
  "livePose": Service(True, 20., 4),
  "liveParameters": Service(True, 20., 5),
  "cameraOdometry": Service(True, 20., 10),
  "thumbnail": Service(True, 1 / 60., 1),
  "onroadEvents": Service(True, 1., 1),
  "carParams": Service(True, 0.02, 1),
  "roadCameraState": Service(True, 20., 20),
  "driverCameraState": Service(True, 20., 20),
  "driverEncodeIdx": Service(False, 20., 1),
  "driverStateV2": Service(True, 20., 10),
  "driverMonitoringState": Service(True, 20., 10),
  "wideRoadEncodeIdx": Service(False, 20., 1),
  "wideRoadCameraState": Service(True, 20., 20),
  "drivingModelData": Service(True, 20., 10),
  "modelV2": Service(True, 20., big_queue=True),
  "managerState": Service(True, 2., 1),
  "uploaderState": Service(True, 0., 1),
  "navInstruction": Service(True, 1., 10),
  "navRoute": Service(True, 0.),
  "navThumbnail": Service(True, 0.),
  "qRoadEncodeIdx": Service(False, 20.),
  "userBookmark": Service(True, 0., 1),
  "soundPressure": Service(True, 10., 10),
  "rawAudioData": Service(False, 20.),
  "bookmarkButton": Service(True, 0., 1),
  "audioFeedback": Service(True, 0., 1),

  # debug
  "uiDebug": Service(True, 0., 1),
  "testJoystick": Service(True, 0.),
  "alertDebug": Service(True, 20., 5),
  "roadEncodeData": Service(False, 20.),
  "driverEncodeData": Service(False, 20.),
  "wideRoadEncodeData": Service(False, 20.),
  "qRoadEncodeData": Service(False, 20.),
  "livestreamWideRoadEncodeIdx": Service(False, 20.),
  "livestreamRoadEncodeIdx": Service(False, 20.),
  "livestreamDriverEncodeIdx": Service(False, 20.),
  "livestreamWideRoadEncodeData": Service(False, 20.),
  "livestreamRoadEncodeData": Service(False, 20.),
  "livestreamDriverEncodeData": Service(False, 20.),
  "customReservedRawData0": Service(True, 0.),
  "customReservedRawData1": Service(True, 0.),
  "customReservedRawData2": Service(True, 0.),
}


def build_header():
  h = ""
  h += "/* THIS IS AN AUTOGENERATED FILE, PLEASE EDIT services.py */\n"
  h += "#ifndef __SERVICES_H\n"
  h += "#define __SERVICES_H\n"

  h += "#include <map>\n"
  h += "#include <string>\n"

  h += "struct service { std::string name; bool should_log; float frequency; int decimation; bool big_queue; };\n"
  h += "static std::map<std::string, service> services = {\n"
  for k, v in SERVICE_LIST.items():
    should_log = "true" if v.should_log else "false"
    decimation = -1 if v.decimation is None else v.decimation
    big_queue = "true" if v.big_queue else "false"
    h += '  { "%s", {"%s", %s, %f, %d, %s}},\n' % \
         (k, k, should_log, v.frequency, decimation, big_queue)
  h += "};\n"

  h += "#endif\n"
  return h


if __name__ == "__main__":
  print(build_header())
